[package]
name = "axgeom"
version = "1.4.4"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "Library that provides ability to extract 1d ranges out of 2d objects."
license = "MIT/Apache-2.0"
repository = "https://github.com/tiby312/axgeom"
keywords = ["geometry", "axis"]
readme = "readme.md"
edition = "2018"

[dependencies]
roots = "0.0.5"
ordered-float = "1.0.2"
num-traits = "0.2.10"
primitive-from = "1.0.2"
