[package]
name = "axgeom"
version = "1.6.9"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "Library that provides ability to extract 1d ranges out of 2d objects."
license = "MIT/Apache-2.0"
repository = "https://github.com/tiby312/axgeom"
keywords = ["geometry", "axis"]
readme = "readme.md"
edition = "2018"

[dependencies]
roots = "0.0.6"
ordered-float = {version="1.0", features=["serde"]}
num-traits = "0.2"
primitive-from = "1.0"
serde={version="1.0", features=["derive"]}
